name: Build and deploy to IBM Cloud Foundry

# Execute on every push to master
on:
  workflow_dispatch

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_REGION: us-east
  IBM_CLOUD_GROUP: default
  IBM_CLOUD_SPACE: dev-us-east
  IBM_CLOUD_ORG: ulidder@us.ibm.com
  MANIFEST_NAME: manifest.yml
  MANIFEST_LOCATION: .
  IBM_CLOUD_API_KEY: ${{secrets.IBM_CLOUD_API_KEY}}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2      

      # A GitHub Action for serializing workflow runs
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: upkarlidder/cf-build-deploy@main
        with:
          github-sha: $GITHUB_SHA
          ibm-cloud-api-key: $IBM_CLOUD_API_KEY
          ibm-cloud-org: $IBM_CLOUD_ORG
          ibm-cloud-resource-group: $IBM_CLOUD_GROUP
          ibm-cloud-region: $IBM_CLOUD_REGION
          ibm-cloud-space: $IBM_CLOUD_SPACE
          working-directory: $MANIFEST_LOCATION